version: '3.5'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - '80:80'
    volumes:
      - ./:/code

    environment:
      -  SECRET_KEY
      -  DEBUG
      -  DATABASE_URL
      -  EMAIL_HOST
      -  DEFAULT_FROM_EMAIL
      -  EMAIL_HOST_USER
      -  EMAIL_HOST_PASSWORD
      -  EMAIL_PORT
      -  EMAIL_USE_TLS
      -  BROKER_URL
      -  SENTRY_CREDENTIALS

  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A checkqrgpcbackend worker -l info
    volumes:
      - ./:/code
    environment:
      -  SECRET_KEY
      -  DEBUG
      -  DATABASE_URL
      -  EMAIL_HOST
      -  DEFAULT_FROM_EMAIL
      -  EMAIL_HOST_USER
      -  EMAIL_HOST_PASSWORD
      -  EMAIL_PORT
      -  EMAIL_USE_TLS
      -  BROKER_URL
      -  SENTRY_CREDENTIALS


  redis:
    image: redis
    sysctls:
      - net.core.somaxconn=65535