FROM python:3.9
WORKDIR /code
COPY ./requirements /code/requirements
COPY ./requirement.txt /code/requirements.txt
RUN pip install --upgrade pip==22.0.0
RUN pip install -r requirements.txt

COPY . /code/

CMD python manage.py runserver 0.0.0.0:8000