version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.testing
    environment:
      -  SECRET_KEY
      -  DEBUG
      -  DATABASE_URL
      -  EMAIL_HOST
      -  DEFAULT_FROM_EMAIL
      -  EMAIL_HOST_USER
      -  EMAIL_HOST_PASSWORD
      -  EMAIL_PORT
      -  EMAIL_USE_TLS
      -  BROKER_URL
      -  SENTRY_CREDENTIALS
