# Generated by Django 4.0 on 2023-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvalidatorcredential',
            name='remote_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalvalidatorcredential',
            name='remote_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='validatorcredential',
            name='remote_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='validatorcredential',
            name='remote_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
