# Generated by Django 4.0 on 2023-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_historicalvalidatorcredential_remote_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvalidatorcredential',
            name='token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='validatorcredential',
            name='token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
