# Generated by Django 4.0 on 2023-05-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationurl',
            name='is_only_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationurl',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplicationurl',
            name='is_only_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplicationurl',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
