# Generated by Django 4.0 on 2023-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_applicationurl_is_only_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='uses_jwt_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationurl',
            name='is_token_validate_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplicationconfiguration',
            name='uses_jwt_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplicationurl',
            name='is_token_validate_url',
            field=models.BooleanField(default=False),
        ),
    ]
